//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _GMTEGRATOR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GM_ERROR_MESSAGES
    {
        public int id { get; set; }
        public string HATA_KODU { get; set; }
        public string HATA_MESAJI { get; set; }
    }
}
