//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _GMTEGRATOR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GM_TBLSTRESIM
    {
        public int INCKEYNO { get; set; }
        public Nullable<int> MAGAZA_ID { get; set; }
        public string STOK_KODU { get; set; }
        public string resim_url1 { get; set; }
        public string resim_url2 { get; set; }
        public string resim_url3 { get; set; }
        public string resim_url4 { get; set; }
        public string resim_url5 { get; set; }
    }
}
