//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _GMTEGRATOR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GM_TBLSTSABIT
    {
        public int INCKEYNO { get; set; }
        public string STOK_KODU { get; set; }
        public string STOK_ADI { get; set; }
        public string STOK_ACIKLAMASI { get; set; }
        public Nullable<decimal> STOK_FIYAT { get; set; }
        public Nullable<int> STOK_ADEDI { get; set; }
        public Nullable<int> STOK_AKTIF_PASIF { get; set; }
        public Nullable<int> MAGAZA_ID { get; set; }
        public string SELLER_STOK_KODU { get; set; }
        public string N11_KATALOG_ID { get; set; }
        public string Hepsiburada_SKU { get; set; }
    }
}
