//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _GMTEGRATOR.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class deartech_3Entities1 : DbContext
    {
        public deartech_3Entities1()
            : base("name=deartech_3Entities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<GM_KULLANICILAR> GM_KULLANICILAR { get; set; }
        public virtual DbSet<GM_STSABITLOG> GM_STSABITLOG { get; set; }
        public virtual DbSet<GM_TBLSTRESIM> GM_TBLSTRESIM { get; set; }
        public virtual DbSet<GM_TBLSTSABIT> GM_TBLSTSABIT { get; set; }
        public virtual DbSet<GM_USER_SYSTEM_SETTINGS> GM_USER_SYSTEM_SETTINGS { get; set; }
        public virtual DbSet<TUM_URUNLER_V> TUM_URUNLER_V { get; set; }
        public virtual DbSet<GM_ERROR_MESSAGES> GM_ERROR_MESSAGES { get; set; }
    }
}
