//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _GMTEGRATOR.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class deartech_3Entities : DbContext
    {
        public deartech_3Entities()
            : base("name=deartech_3Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<GM_TBLSTRESIM> GM_TBLSTRESIM { get; set; }
        public virtual DbSet<GM_TBLSTSABIT> GM_TBLSTSABIT { get; set; }
    }
}
